// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tehdaizgsltynxefecui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlaGRhaXpnc2x0eW54ZWZlY3VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjUxMjgsImV4cCI6MjA3MjI0MTEyOH0.s9f9kLMZ5h1fqsqSUQd981NZ2nuEdnFhKcjTU27ZSr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});